### ISSUE TITLE
Cannot use 'ms' (type *messageState) as the type protoreflect.Message

### ISSUE THREAD

**Issue by liyongjun1** [golang/protobuf#1393]
**What version of protobuf and what language are you using?**
Version: protoc-gen-go v1.27.1 protoc        v3.17.3

**What did you do?**
I use protoc to generate the project file for Go
```shell
 protoc --go_out=./ protobuf/hello.proto
```
protobuf/hello.proto is as below
```
syntax = "proto3";

package test.hello;
option go_package = "test/hello";

service HelloService {
  rpc Hello(HelloItem) returns (CommonRsp) {}
}

message HelloItem {
  string username = 1;
}

message CommonRsp {
  int32 retcode = 1;
  string message = 2;
}
```
Then I get the file generated by protoc (hello.pb.go)

**What did you expect to see?**
cause a compilation error after I open the generated go file with GoLand
**What did you see instead?**
Cannot use 'ms' (type *messageState) as the type protoreflect.Message
Type does not implement 'protoreflect.Message'
need the method: ProtoMethods() *methods
have the method: ProtoMethods() *protoiface.Methods
![image](https://user-images.githubusercontent.com/19545622/144703550-96bf69ea-c367-499c-997d-c5834e5df4f1.png)

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment?**
Mac OS:11.6.1 
go version go1.17.1 darwin/amd6
```
➜  bin brew list protobuf
/usr/local/Cellar/protobuf/3.17.3_1/bin/protoc
/usr/local/Cellar/protobuf/3.17.3_1/include/google/ (119 files)
/usr/local/Cellar/protobuf/3.17.3_1/lib/libprotobuf-lite.28.dylib
/usr/local/Cellar/protobuf/3.17.3_1/lib/libprotobuf.28.dylib
/usr/local/Cellar/protobuf/3.17.3_1/lib/libprotoc.28.dylib
/usr/local/Cellar/protobuf/3.17.3_1/lib/pkgconfig/ (2 files)
/usr/local/Cellar/protobuf/3.17.3_1/lib/python3.10/ (53 files)
/usr/local/Cellar/protobuf/3.17.3_1/lib/python3.9/ (53 files)
/usr/local/Cellar/protobuf/3.17.3_1/lib/ (6 other files)
/usr/local/Cellar/protobuf/3.17.3_1/share/emacs/site-lisp/protobuf/protobuf-mode.el
/usr/local/Cellar/protobuf/3.17.3_1/share/protobuf/ (20 files)
```

**Comment by puellanivis** [comment]
🤔 Could you also post the `go.mod` that you’re working under?

**Comment by liyongjun1** [comment]
go 1.17

require (
	google.golang.org/grpc v1.42.0
	google.golang.org/protobuf v1.27.1
)

require (
	github.com/golang/protobuf v1.5.0 // indirect
	golang.org/x/net v0.0.0-20200822124328-c89045814202 // indirect
	golang.org/x/sys v0.0.0-20200323222414-85ca7c5b95cd // indirect
	golang.org/x/text v0.3.0 // indirect
	google.golang.org/genproto v0.0.0-20200526211855-cb27e3aa2013 // indirect
)
![image](https://user-images.githubusercontent.com/19545622/144777392-41422251-4646-4a91-86a4-92c5a187098e.png)

**Comment by JimChen119** [comment]
I have the same problem in Goland 2021.3. 
Although there are errors, but the code compiles normally. 
Execution is also normal.  I guess it's a problem with goland.

**Comment by liyongjun1** [comment]
yup, execution is normal, only have the  code compilation error

**Comment by puellanivis** [comment]
It sounds like the bug is with GoLand then?

**Comment by liyongjun1** [comment]
I'm going to reinstall the old version of GoLand, to check whether the compilation error is exist or not

**Comment by JimChen119** [comment]
@liyongjun1 ,   Please tell me if there is a result.  Thanks

**Comment by liyongjun1** [comment]
@puellanivis @JimChen119 I reinstall the old version(GoLand 2021.2.4),it works well now, doesn't show compilation error any more. The issue I raised may be the bug of GoLand 2021.3. cuz I Found the compilation error just after the time when I upgrade the IDE to the latest version

**Comment by GGXXLL** [comment]
The same problem, without modifying the code, the problem occurred after goland was updated to 2021.3

**Comment by liyongjun1** [comment]
I see, I just wanted to report the bug for GoLand

**Comment by neild** [comment]
Closing since this is a GoLand bug and there's not much we can do about it here.

**Comment by gcsfred2** [comment]
Same problem.

**Comment by b1gdea1** [comment]
![image](https://user-images.githubusercontent.com/59244373/146947798-5a6c5a3d-194b-488c-a2e6-d5b49a100cab.png)
after updated to 2021.3.1, the error we met was gone.
